//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoStudio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentDetails
    {
        public int ID { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<System.DateTime> TxnDate { get; set; }
        public string PaymentMode { get; set; }
        public string PaymentCategory { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual tbl_PaymentMaster tbl_PaymentMaster { get; set; }
    }
}
