//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoStudio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_PaymentMaster()
        {
            this.tbl_PaymentDetails = new HashSet<tbl_PaymentDetails>();
        }
    
        public int PaymentId { get; set; }
        public int ReservationId { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public Nullable<decimal> FullAmount { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public Nullable<bool> Settle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PaymentDetails> tbl_PaymentDetails { get; set; }
        public virtual tbl_ReservationMaster tbl_ReservationMaster { get; set; }
    }
}
