//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoStudio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SMSEmailPosting
    {
        public long ID { get; set; }
        public string Type { get; set; }
        public string RefNo { get; set; }
        public string PhoneNumber { get; set; }
        public string email { get; set; }
        public string Message { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public bool Isposted { get; set; }
        public Nullable<System.DateTime> PostedTime { get; set; }
        public string Narration { get; set; }
        public string ResponseCode { get; set; }
    }
}
