//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoStudio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address { get; set; }
        public string ContactNum { get; set; }
        public string EmailAddress { get; set; }
        public string Password { get; set; }
        public string UserType { get; set; }
        public Nullable<int> BrachID { get; set; }
    
        public virtual tbl_Branch tbl_Branch { get; set; }
        public virtual tbl_EmpTypeRef tbl_EmpTypeRef { get; set; }
    }
}
