//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoStudio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Branch()
        {
            this.tbl_User = new HashSet<tbl_User>();
        }
    
        public int BarnchID { get; set; }
        public string BranchName { get; set; }
        public string Address { get; set; }
        public string ContactNumbe { get; set; }
        public string BranchEmail { get; set; }
        public Nullable<int> MangerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_User> tbl_User { get; set; }
    }
}
