//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoStudio.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ReservationMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_ReservationMaster()
        {
            this.tbl_PaymentMaster = new HashSet<tbl_PaymentMaster>();
        }
    
        public int ReservationId { get; set; }
        public int CustomerID { get; set; }
        public string EvenType { get; set; }
        public string FunctionType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }
        public Nullable<bool> IsPayCompleate { get; set; }
        public Nullable<bool> IsReservationCompleate { get; set; }
    
        public virtual tbl_ChargTyperef tbl_ChargTyperef { get; set; }
        public virtual tbl_customer tbl_customer { get; set; }
        public virtual tbl_EventType tbl_EventType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PaymentMaster> tbl_PaymentMaster { get; set; }
    }
}
